name: forest_filter 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - pysam==0.16.0.1
  - pysamstats==1.1.2
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - blast 
  - samtools
  - scikit-learn
  - pyvcf
