name: tests
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.9]
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda 
        uses: s-weigand/setup-conda@v1
        with:
          environment-file: environment.yml
    - name: Test 
      run: python -m unittest test/test_train.py
